SpadesX/SpadesX

CONTRIBUTORS.md
Source/Main.c
Source/Server.c
Source/Util/JSONHelpers.h
Source/Util/Types.h

Made these changes before I found out that the config file together with map are located in the source directory, though they aren't copied to the build directory. What a dumbass!
Anyway, I think that having a fallback for the config values is a great feature.
Also, while rewriting config reading routines, I've found these lines of code: 
https://github.com/SpadesX/SpadesX/blob/9a5b9f10d8f13c0e0f5910f2d92d8dc8660cf304/Source/Server.c#L180-L185
Is it supposed to read only 2 elements from the 3 element array? Or is it just me having an amount of braincells that is roughly equal to the size of said arrays?

Add fallbacks for the config variables that can't be found in the config file

---

Source/Server/Packets/PacketManager.c

The SMG delay was set to 110ms, which is incorrect. It should be 100ms as seen on [OpenSpades](https://github.com/yvt/openspades/blob/f141208322953a4473eb42019c578e87a8a36640/Sources/Client/Weapon.cpp#L231) and [BetterSpades](https://github.com/xtreme8000/BetterSpades/blob/f83760ec1ae4dff58b8ad04109c3e7c6d562e2c8/src/weapon.c#L103).

PacketManager.c: Change SMG delay to 100ms

---

.gitignore

Adds the `.idea` directory and CMake debug files to gitignore.

Add JetBrains and CMake Debug files to gitignore

---

Source/Server/Packets/BlockAction.c
Source/Util/Enums.h

SpadesX does not currently keep track of block damage, so we can't really check if block destruction is done too fast at the moment.
Fixes:
- Blocks not being destroyed when hit (detected as rapid shooting) if their HP isn't 100
- Lowering expected delay for rifle and SMG in BlockAction.c
- Lowering spade delay in Enums.h

Temporary fix for weapon/spade BlockAction delay

---

Source/Server/Player.c

Velocity does not get reset when a player dies mid-air (can happen from /kill or if shot by another player), causing the player to get fall damage when they respawn.
Fixes:
- Velocity not being reset on respawn, causing fall damage if the player was in the air
- Setting all velocity values to `0` on `set_player_respawn_point` in Player.c

Player.c: Reset velocity on respawn

---

Source/Server/Console.c

Fixes:
- Server not compiling under MinGW due to sleep() and write() not existing
- Using Win32 `Sleep()` and removing the `write()` check.

Update Console.c to compile under MinGW

---

Source/Server/Packets/BlockAction.c
Source/Server/Packets/BlockLine.c
Source/Server/Packets/ExistingPlayer.c
Source/Server/Player.c
Source/Server/Structs/PlayerStruct.h

Fixes:
- BlockLine not being sent to the right players (it was sent to the same player many times, instead of once to each player)
- Joining and seeing players holding a black block instead of the correct color
- BlockLine: Using the correct variable (`player` is wrong)
- ExistingPlayer: Using the `player->tool_color` variable, and remove `player->color` which was unused

Fix ExistingPlayer color and BlockLine

---

Source/Util/Notice.c

OpenSpades requires the server to send messages with 0xFF at the beginning in order for them to be treated as UTF-8, otherwise they are treated as CP437. Not sending the byte causes unicode text to show up as garbled.
Fixes:
- Welcome/periodic messages in config showing up as garbled text if unicode characters are used
- Adding the magic byte OpenSpades expects for UTF-8 support

Notice.c: Add UTF-8 magic byte for OpenSpades

---

Source/Server/Commands/Clin.c

Fixes:
- Server crashing when `/clin` is executed from console
- /clin not letting players check other players' client
- Adding the required code to let players/console do `/clin #ID`

Clin.c: Allow using /clin on other players

---

Source/Server/Player.c
Source/Server/Server.c
Source/Util/JSONHelpers.h

Fixes:
- Being only able to use X and Y in spawn coordinates
- Out-of-bounds read in JSONHelpers
- Adding Z axis in coordinates and spawnpoint checks
- Using fallback values if int array is smaller than expected

Add 3D spawn locations

---

Source/Server/Packets/Grenade.c
Source/Server/Packets/OrientationData.c
Source/Server/Packets/PositionData.c
Source/Util/CMakeLists.txt
Source/Util/Checks/VectorChecks.c
Source/Util/Checks/VectorChecks.h

Fixes:
- Server freezing when grenades with invalid floats as position or velocity are sent
- Player disappearing in VOXLAP/BetterSpades when an orientation with invalid floats is sent
- Check all packets that have floats for nan/inf and drop them
- Slightly cleanup some related code along the way

Server: Check for invalid floats in all packets

---

Source/Server/Packets/PositionData.c

The position checks we did previously greatly reduce the power of noclip, however, it is still possible to go through blocks at slow speed.
This fix reduces the effectiveness of noclip even further by not allowing movement when the player is fully covered in blocks (3 blocks from feet to head).
Fixes:
- Noclip protection not preventing movement in cases where movement is not possible
- Drop PositionData packets when the player can't normally move ingame

PositionData.c: Check if player is in solid blocks

---

Source/Server/Packets/BlockLine.c
Source/Util/Checks/BlockChecks.c

Fixes:
- Being able to place block lines midair and on water
- Being able to place regular blocks on water
- Add a Z check to `is_block_placable` to prevent placing blocks on/under water
- Add the same `is_block_placable` checks as BlockAction to BlockLine

Prevent bad BlockLine placements

---

Source/Main.c
Source/Server/Commands/CommandManager.c
Source/Server/Events.h
Source/Server/Map.c
Source/Server/Nodes.c
Source/Server/Packets/BlockAction.c
Source/Server/Packets/BlockLine.c
Source/Server/Packets/ExistingPlayer.c
Source/Server/Packets/Grenade.c
Source/Server/Packets/MapStart.c
Source/Server/Packets/Message.c
Source/Server/Packets/PacketManager.c
Source/Server/Player.c
Source/Util/Alloc.c
Source/Util/Alloc.h
Source/Util/CMakeLists.txt
Source/Util/Compress.c
Source/Util/DataStream.c

Fixes:
- Repeated allocation checks in some places
- Some missing checks (mostly `calloc`s)
- Create wrapper functions `spadesx_malloc` and `spadesx_calloc` for malloc/calloc respectively
- Replace all uses of malloc/calloc with our own wrappers

All: Check for memory allocation failures everywhere

---

Source/Server/Packets/ExistingPlayer.c

Fixes:
- Compilation on GCC 13.1.1 20230429.
- Half of #72.
- Changing the dstsize of a strlcat for distinguishing player names from 17 octets, which is far too large for a player name, to 16 octets (INCLUDING the NULL terminator).

ExistingPlayer.c: Use correct dstsize for strlcat.

---

Source/Server/IntelTent.c
Source/Server/Packets/ChangeTeam.c
Source/Server/Packets/ExistingPlayer.c
Source/Server/Packets/IntelCapture.c
Source/Server/Packets/IntelDrop.c
Source/Server/Packets/IntelPickup.c
Source/Server/Packets/KillAction.c
Source/Server/Packets/Message.c
Source/Server/Packets/ShortPlayerData.c
Source/Server/Player.c
Source/Util/Enums.h

You might want to skim through the code first. Also I had some formatter installed and it changed some other formatting, but it's fine I hope. I couldn't find any way to break spectator mode now but I don't know all the edge cases in my head. 
Tested in BeS, OS
Fixes:
- spectator mode completely broken
- you can now view players POV too
- z spawn offset used same as in pyspades, resulting in the familiar "drop on spawn"

(mostly) fix spectator and fix players spawning inside blocks

---

CMakeLists.txt

Same as SpadesX/enet#1, required for #77.

CMakeLists.txt: Set project LANGUAGES to C

---

CMakeLists.txt
Extern/CMakeLists.txt

Use case: without this parameter, the Docker container would attempt to fetch the submodules, which requires installing Git, thus making the build process longer. It's better to run the `git submodules update` command on the build machine and then run the Dockerfile.

CMakeLists.txt: Make the Git submodule fetch optional

---

.gitignore

Adds `._.git` and `.DS_Store` to gitignore so I don't have to rm them all the time 😆

gitignore: add macOS files to ignore

---

.github/workflows/cmake.yml
CMakeLists.txt
Dockerfile
README.md
Source/Server/Packets/ExistingPlayer.c
Source/Server/Player.c
Source/Server/Structs/PlayerStruct.h

The code used to ensure usernames are unique for online players has been largely rewritten in this PR.
The major takeaways are:
- This PR aims to resolve #72; it appears to have no trouble modifying players' usernames to be unique regardless of the length of their desired name or their player ID as a string.
- Removed use case of `libbsd`, as this new version does not use `strlcat`.
- Some other cleanup may be needed with CMake and documentation to finish removing this now-unused dependency.
- I'm almost certain there is a lot to improve with this code - C strings are my greatest weakness, lol. Please lend a hand in updating the code as you see fit.
- I'm particularly worried about the use of standard string functions that aren't aware of a max bound they should restrict themselves to. …

Rewrite 'unique username system', removing libbsd dependency
